Algoritmo "teste"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2020
Var
x,y : real
// Seção de Declarações das variáveis 

  

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreva ("digite o valor de x")
  leia (x)
  y <- 3*x+2
  escreva ("Resultado da operação",y)
 
Fimalgoritmo